### ISSUE TITLE
How would we combine iterm/kitty integration?

### ISSUE THREAD

**Issue by Techcable** [jnoortheen/xontrib-term-integrations#1]
Hi! Came here from xonsh/xonsh#4623 :)

As far as I'm aware, [kitty's requirements for escape sequences](https://sw.kovidgoyal.net/kitty/shell-integration/#notes-for-shell-developers) are a subset of iTerm2's. The only extra thing needed is `$PS2`.

> The prompt marking sequences are the same except that kityt needs less (more dont do any harm) and it marks PS2 which iterm doesnt.

Given how much overlap there seems to be, I think it makes the most sense to combine the kitty/iterm integration wherever possible.

Does it make more sense to:
1. Turn this into a common plugin that supports both (maybe called `fancy-term` or `term-integration` or something?)
2. Have separate xontribs for both, but move common code into a library (this is probably better)

It seems you already have the bulk of the work done for iTerm2. That's amazing 😄 

I'm not super familiar with how "xontrib libraries" would work. What are your thoughts on this?

**Comment by jnoortheen** [comment]
I was also thinking the same. I have added a kitty module.

**Comment by jnoortheen** [comment]
@amitkot you have to install xonsh from main branch. It has the required fix. There is no special installation needed for kitty.

**Comment by jnoortheen** [comment]
I have updated the readme file to mention this

**Comment by amitkot** [comment]
@jnoortheen Thanks! This is not urgent for me so I will wait until the next Xonsh release to check it.
