### ISSUE TITLE
Error trying to install source checkout with `pip install -e`

### ISSUE THREAD

**Issue by Techcable** [jnoortheen/xontrib-term-integrations#2]
````
Obtaining file:///Users/techcable/git/xontrib-term-integrations
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
ERROR: Project file:///Users/techcable/git/xontrib-term-integrations has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
````

Could you please add a `setup.cfg` or `setup.py` ❤️

**Comment by jnoortheen** [comment]
Please checkout poetry. Also it is possible to build using pip, I think one need to install poetry-core to do so. I do not want dependencies defined in multiple places.

**Comment by jnoortheen** [comment]
This link will help you https://github.com/python-poetry/poetry/issues/34#issuecomment-997519115

**Comment by Techcable** [comment]
![My Python Evironment](https://xkcd.com/1987/)

**Comment by Techcable** [comment]
![My Python Environment](https://imgs.xkcd.com/comics/python_environment_2x.png)

❤️
