### ISSUE TITLE
Escape characters shown in prompt

### ISSUE THREAD

**Issue by engdan77** [jnoortheen/xontrib-term-integrations#3]
Hi, excited to see this project and been looking forward to a working xonsh successfully integrated with iterm2 (MacOS).
I tried this and not certain if this is something I've missed or any other obvious settings at my end, but when having this loaded (with or without powerline2) it looks that there are some reoccurring escape-characters..

In such case I can supply anything that would help look into this or any advice what to try next..?

With xontrib-term-integration loaded
<img width="119" alt="image" src="https://user-images.githubusercontent.com/8431437/149482106-11140f78-5a6d-4afb-a2d8-e2f398da3d3f.png">

Without xontrib-term-integration loaded
![image](https://user-images.githubusercontent.com/8431437/149482608-8596a4f1-6ea6-4835-8a3a-49b883ed5062.png)

Kind regards,
Daniel

**Comment by jnoortheen** [comment]
It works with the xonsh-main branch (not yet released). You could install it using pip+github url and try again.

**Comment by jnoortheen** [comment]
Also You can do a quick test with readline backend (only ptk backend needs this fix) like below.  

```
xonsh --shell=rl
```
